
image: continuumio/miniconda3

before_script:
  # creating and entering conda enviroment
  - conda env create -f environment.yml
  - source activate cobramod
  - conda info

# build1:
#   stage: build
#   script:
#     - echo "Do your build here"

test:
  stage: test
  script:
    - python3 -m unittest discover -s tests/ -v
