
image: continuumio/miniconda3

before_script:
  # creating and entering conda enviroment
  - conda env create -f environment.yml
  - source activate cobramod
  - conda info

# build1:
#   stage: build
#   script:
#     - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

# test2:
#   stage: test
#   script:
#     - echo "Do another parallel test here"
#     - echo "For example run a lint test"

# deploy1:
#   stage: deploy
#   script:
#     - echo "Do your deploy here"
